/* eslint-disable max-len */
export const nasdaq103 = {
  "AAPL": "Apple Inc",
  "MSFT": "Microsoft Corp",
  "AMZN": "Amazon.com Inc",
  "NVDA": "NVIDIA Corp",
  "META": "Meta Platforms Inc",
  "AVGO": "Broadcom Inc",
  "GOOGL": "Alphabet Inc",
  "GOOG": "Alphabet Inc",
  "TSLA": "Tesla Inc",
  "ADBE": "Adobe Inc",
  "COST": "Costco Wholesale Corp",
  "PEP": "PepsiCo Inc",
  "AMD": "Advanced Micro Devices Inc",
  "NFLX": "Netflix Inc",
  "CSCO": "Cisco Systems Inc",
  "TMUS": "T-Mobile US Inc",
  "INTC": "Intel Corp",
  "CMCSA": "Comcast Corp",
  "INTU": "Intuit Inc",
  "QCOM": "QUALCOMM Inc",
  "AMGN": "Amgen Inc",
  "TXN": "Texas Instruments Inc",
  "HON": "Honeywell International Inc",
  "AMAT": "Applied Materials Inc",
  "BKNG": "Booking Holdings Inc",
  "SBUX": "Starbucks Corp",
  "ISRG": "Intuitive Surgical Inc",
  "MDLZ": "Mondelez International Inc",
  "GILD": "Gilead Sciences Inc",
  "ADP": "Automatic Data Processing Inc",
  "LRCX": "Lam Research Corp",
  "ADI": "Analog Devices Inc",
  "PDD": "PDD Holdings Inc ADR",
  "VRTX": "Vertex Pharmaceuticals Inc",
  "REGN": "Regeneron Pharmaceuticals Inc",
  "PANW": "Palo Alto Networks Inc",
  "SNPS": "Synopsys Inc",
  "MU": "Micron Technology Inc",
  "MELI": "MercadoLibre Inc",
  "KLAC": "KLA Corp",
  "CDNS": "Cadence Design Systems Inc",
  "CSX": "CSX Corp",
  "PYPL": "PayPal Holdings Inc",
  "MAR": "Marriott International Inc/MD",
  "ASML": "ASML Holding NV",
  "ABNB": "Airbnb Inc",
  "ORLY": "O'Reilly Automotive Inc",
  "MNST": "Monster Beverage Corp",
  "LULU": "Lululemon Athletica Inc",
  "WDAY": "Workday Inc",
  "CTAS": "Cintas Corp",
  "CHTR": "Charter Communications Inc",
  "NXPI": "NXP Semiconductors NV",
  "CRWD": "Crowdstrike Holdings Inc",
  "PCAR": "PACCAR Inc",
  "ADSK": "Autodesk Inc",
  "MCHP": "Microchip Technology Inc",
  "DXCM": "Dexcom Inc",
  "CPRT": "Copart Inc",
  "KDP": "Keurig Dr Pepper Inc",
  "MRVL": "Marvell Technology Inc",
  "PAYX": "Paychex Inc",
  "ROST": "Ross Stores Inc",
  "KHC": "Kraft Heinz Co/The",
  "IDXX": "IDEXX Laboratories Inc",
  "AEP": "American Electric Power Co Inc",
  "ODFL": "Old Dominion Freight Line Inc",
  "FTNT": "Fortinet Inc",
  "EXC": "Exelon Corp",
  "AZN": "AstraZeneca PLC ADR",
  "EA": "Electronic Arts Inc",
  "FAST": "Fastenal Co",
  "CTSH": "Cognizant Technology Solutions Corp",
  "CEG": "Constellation Energy Corp",
  "BIIB": "Biogen Inc",
  "DDOG": "Datadog Inc",
  "XEL": "Xcel Energy Inc",
  "VRSK": "Verisk Analytics Inc",
  "CSGP": "CoStar Group Inc",
  "ON": "ON Semiconductor Corp",
  "BKR": "Baker Hughes Co",
  "TTD": "Trade Desk Inc/The",
  "GEHC": "GE HealthCare Technologies Inc",
  "MRNA": "Moderna Inc",
  "ZS": "Zscaler Inc",
  "GFS": "GLOBALFOUNDRIES Inc",
  "TEAM": "Atlassian Corp",
  "DLTR": "Dollar Tree Inc",
  "FANG": "Diamondback Energy Inc",
  "WBD": "Warner Bros Discovery Inc",
  "ANSS": "ANSYS Inc",
  "EBAY": "eBay Inc",
  "WBA": "Walgreens Boots Alliance Inc",
  "ILMN": "Illumina Inc",
  "ZM": "Zoom Video Communications Inc",
  "SIRI": "Sirius XM Holdings Inc",
  "ALGN": "Align Technology Inc",
  "ENPH": "Enphase Energy Inc",
  "JD": "JD.com Inc ADR",
  "LCID": "Lucid Group Inc",
  "QBTS": "D-Wave Quantum Inc. Common Shares",
  "BAYRY": "Bayer AG ADR",
  "BABA": "Alibaba Group Holding Ltd.",
};

export const bist50 = {
  AEFES: "ANADOLU EFES",
  AKBNK: "AKBANK",
  AKSEN: "AKSA ENERJI",
  ALARK: "ALARKO HOLDING",
  ARCLK: "ARCELIK",
  ASELS: "ASELSAN",
  ASTOR: "ASTOR ENERJI",
  BIMAS: "BIM MAGAZALAR",
  CANTE: "CAN2 TERMIK",
  CIMSA: "CIMSA",
  CWENE: "CW ENERJI",
  DOAS: "DOGUS OTOMOTIV",
  DOHOL: "DOGAN HOLDING",
  EKGYO: "EMLAK KONUT GMYO",
  ENJSA: "ENERJISA ENERJI",
  ENKAI: "ENKA INSAAT",
  EREGL: "EREGLI DEMIR CELIK",
  EUPWR: "EUROPOWER ENERJI",
  FROTO: "FORD OTOSAN",
  GARAN: "GARANTI BANKASI",
  GESAN: "GIRISIM ELEKTRIK SANAYI",
  GUBRF: "GUBRE FABRIK.",
  HALKB: "T. HALK BANKASI",
  HEKTS: "HEKTAS",
  ISCTR: "IS BANKASI (C)",
  KCHOL: "KOC HOLDING",
  KONTR: "KONTROLMATIK TEKNOLOJI",
  KOZAA: "KOZA MADENCILIK",
  KOZAL: "KOZA ALTIN",
  KRDMD: "KARDEMIR (D)",
  MGROS: "MIGROS TICARET",
  ODAS: "ODAS ELEKTRIK",
  OYAKC: "OYAK CIMENTO",
  PETKM: "PETKIM",
  PGSUS: "PEGASUS",
  SAHOL: "SABANCI HOLDING",
  SASA: "SASA POLYESTER",
  SISE: "SISE CAM",
  SMRTG: "SMART GUNES ENERJISI TEK.",
  TAVHL: "TAV HAVALIMANLARI",
  TCELL: "TURKCELL",
  THYAO: "TURK HAVA YOLLARI",
  TKFEN: "TEKFEN HOLDING",
  TOASO: "TOFAS OTO. FAB.",
  TSKB: "T.S.K.B.",
  TTKOM: "TURK TELEKOM",
  TUPRS: "TUPRAS",
  VAKBN: "VAKIFLAR BANKASI",
  VESTL: "VESTEL",
  YKBNK: "YAPI VE KREDI BANK.",
};

export const forex30 = {
  "USD": "United States Dollar",
  "EURUSD": "Euro",
  "JPYUSD": "Japanese Yen",
  "GBPUSD": "British Pound",
  "AUDUSD": "Australian Dollar",
  "CADUSD": "Canadian Dollar",
  "CHFUSD": "Swiss Franc",
  "NZDUSD": "New Zealand Dollar",
  "ZARUSD": "South African Rand",
  "SGDUSD": "Singapore Dollar",
  "HKDUSD": "Hong Kong Dollar",
  "SEKUSD": "Swedish Krona",
  "NOKUSD": "Norwegian Krone",
  "MXNUSD": "Mexican Peso",
  "INRUSD": "Indian Rupee",
  "RUBUSD": "Russian Ruble",
  "BRLUSD": "Brazilian Real",
  "KRWUSD": "South Korean Won",
  "TRYUSD": "Turkish Lira",
  "IDRUSD": "Indonesian Rupiah",
  "PLNUSD": "Polish Złoty",
  "THBUSD": "Thai Baht",
  "HUFUSD": "Hungarian Forint",
  "CZKUSD": "Czech Koruna",
  "ILSUSD": "Israeli New Shekel",
  "PHPUSD": "Philippine Peso",
  "MYRUSD": "Malaysian Ringgit",
  "DKKUSD": "Danish Krone",
  "XAUUSD": "Gold",
  "XAGUSD": "Silver",
};


export const crypto100 = {
  "bitcoin": {symbol: "btc", name: "Bitcoin"},
  "ethereum": {symbol: "eth", name: "Ethereum"},
  "tether": {symbol: "usdt", name: "Tether"},
  "binancecoin": {symbol: "bnb", name: "BNB"},
  "ripple": {symbol: "xrp", name: "XRP"},
  "solana": {symbol: "sol", name: "Solana"},
  "usd-coin": {symbol: "usdc", name: "USDC"},
  "staked-ether": {symbol: "steth", name: "Lido Staked Ether"},
  "cardano": {symbol: "ada", name: "Cardano"},
  "dogecoin": {symbol: "doge", name: "Dogecoin"},
  "tron": {symbol: "trx", name: "TRON"},
  "chainlink": {symbol: "link", name: "Chainlink"},
  "the-open-network": {symbol: "ton", name: "Toncoin"},
  "avalanche-2": {symbol: "avax", name: "Avalanche"},
  "matic-network": {symbol: "matic", name: "Polygon"},
  "polkadot": {symbol: "dot", name: "Polkadot"},
  "wrapped-bitcoin": {symbol: "wbtc", name: "Wrapped Bitcoin"},
  "shiba-inu": {symbol: "shib", name: "Shiba Inu"},
  "litecoin": {symbol: "ltc", name: "Litecoin"},
  "dai": {symbol: "dai", name: "Dai"},
  "bitcoin-cash": {symbol: "bch", name: "Bitcoin Cash"},
  "uniswap": {symbol: "uni", name: "Uniswap"},
  "okb": {symbol: "okb", name: "OKB"},
  "leo-token": {symbol: "leo", name: "LEO Token"},
  "stellar": {symbol: "xlm", name: "Stellar"},
  "kaspa": {symbol: "kas", name: "Kaspa"},
  "monero": {symbol: "xmr", name: "Monero"},
  "ethereum-classic": {symbol: "etc", name: "Ethereum Classic"},
  "true-usd": {symbol: "tusd", name: "TrueUSD"},
  "cosmos": {symbol: "atom", name: "Cosmos Hub"},
  "crypto-com-chain": {symbol: "cro", name: "Cronos"},
  "filecoin": {symbol: "fil", name: "Filecoin"},
  "internet-computer": {symbol: "icp", name: "Internet Computer"},
  "near": {symbol: "near", name: "NEAR Protocol"},
  "hedera-hashgraph": {symbol: "hbar", name: "Hedera"},
  "lido-dao": {symbol: "ldo", name: "Lido DAO"},
  "aptos": {symbol: "apt", name: "Aptos"},
  "thorchain": {symbol: "rune", name: "THORChain"},
  "bittensor": {symbol: "tao", name: "Bittensor"},
  "immutable-x": {symbol: "imx", name: "Immutable"},
  "mantle": {symbol: "mnt", name: "Mantle"},
  "vechain": {symbol: "vet", name: "VeChain"},
  "blockstack": {symbol: "stx", name: "Stacks"},
  "binance-usd": {symbol: "busd", name: "BUSD"},
  "optimism": {symbol: "op", name: "Optimism"},
  "quant-network": {symbol: "qnt", name: "Quant"},
  "the-graph": {symbol: "grt", name: "The Graph"},
  "aave": {symbol: "aave", name: "Aave"},
  "arbitrum": {symbol: "arb", name: "Arbitrum"},
  "injective-protocol": {symbol: "inj", name: "Injective"},
  "render-token": {symbol: "rndr", name: "Render"},
  "maker": {symbol: "mkr", name: "Maker"},
  "rocket-pool-eth": {symbol: "reth", name: "Rocket Pool ETH"},
  "elrond-erd-2": {symbol: "egld", name: "MultiversX"},
  "terra-luna": {symbol: "lunc", name: "Terra Luna Classic"},
  "celestia": {symbol: "tia", name: "Celestia"},
  "ordinals": {symbol: "ordi", name: "ORDI"},
  "algorand": {symbol: "algo", name: "Algorand"},
  "flow": {symbol: "flow", name: "Flow"},
  "havven": {symbol: "snx", name: "Synthetix Network"},
  "theta-token": {symbol: "theta", name: "Theta Network"},
  "first-digital-usd": {symbol: "fdusd", name: "First Digital USD"},
  "bitcoin-cash-sv": {symbol: "bsv", name: "Bitcoin SV"},
  "iota": {symbol: "iota", name: "IOTA"},
  "kucoin-shares": {symbol: "kcs", name: "KuCoin"},
  "the-sandbox": {symbol: "sand", name: "The Sandbox"},
  "axie-infinity": {symbol: "axs", name: "Axie Infinity"},
  "fantom": {symbol: "ftm", name: "Fantom"},
  "gala": {symbol: "gala", name: "GALA"},
  "wemix-token": {symbol: "wemix", name: "WEMIX"},
  "decentraland": {symbol: "mana", name: "Decentraland"},
  "neo": {symbol: "neo", name: "NEO"},
  "eos": {symbol: "eos", name: "EOS"},
  "whitebit": {symbol: "wbt", name: "WhiteBIT Coin"},
  "kava": {symbol: "kava", name: "Kava"},
  "tezos": {symbol: "xtz", name: "Tezos"},
  "mina-protocol": {symbol: "mina", name: "Mina Protocol"},
  "conflux-token": {symbol: "cfx", name: "Conflux"},
  "pyth-network": {symbol: "pyth", name: "Pyth Network"},
  "bitget-token": {symbol: "bgb", name: "Bitget Token"},
  "usdd": {symbol: "usdd", name: "USDD"},
  "xdce-crowd-sale": {symbol: "xdc", name: "XDC Network"},
  "terra-luna-2": {symbol: "luna", name: "Terra"},
  "klay-token": {symbol: "klay", name: "Klaytn"},
  "frax": {symbol: "frax", name: "Frax"},
  "pepe": {symbol: "pepe", name: "Pepe"},
  "frax-ether": {symbol: "frxeth", name: "Frax Ether"},
  "illuvium": {symbol: "ilv", name: "Illuvium"},
  "sui": {symbol: "sui", name: "Sui"},
  "tokenize-xchange": {symbol: "tkx", name: "Tokenize Xchange"},
  "frax-share": {symbol: "fxs", name: "Frax Share"},
  "cheelee": {symbol: "cheel", name: "Cheelee"},
  "sei-network": {symbol: "sei", name: "Sei"},
  "pancakeswap-token": {symbol: "cake", name: "PancakeSwap"},
  "rocket-pool": {symbol: "rpl", name: "Rocket Pool"},
  "chiliz": {symbol: "chz", name: "Chiliz"},
  "apecoin": {symbol: "ape", name: "ApeCoin"},
  "ecash": {symbol: "xec", name: "eCash"},
  "blur": {symbol: "blur", name: "Blur"},
  "binance-eth": {symbol: "beth", name: "Binance ETH staking"},
};
/* eslint-enable max-len */
